{{- define "common.mysql-secret" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.secretName }}
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.database.rootPassword | b64enc | quote }}
{{- end -}}
