{{- define "common.redis-secret" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.redisSecretName }}
type: Opaque
data:
  SPRING_DATA_REDIS_PASSWORD: {{ .Values.global.redisPassword | b64enc | quote }}
{{- end -}}