spring:
  application:
    name: grades_service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/grades_service?serverTimezone=Europe/Warsaw
    username: root
    password: admin
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/jwks.json
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 20
        permittedNumberOfCallsInHalfOpenState: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 15s
  timelimiter:
    configs:
      default:
        timeoutDuration: 10s
        cancelRunningFuture: false

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"
  endpoint:
    health:
      show-details: never
      probes:
        enabled: true
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} %5p [${spring.application.name},%X{trace_id},%X{span_id}] %logger{36} - %msg%n"
  level:
    org:
      zalando:
        logbook: trace

server:
  port: 9000