deploymentName: grades-deployment
serviceName: grades
appLabel: grades_service
appName: grades_service

replicaCount: 1

image:
  repository: student_gradebook/grades_service
  tag: prod

containerPort: 9000

service:
  type: ClusterIP
  port: 9000
  targetPort: 9000

appname_enabled: true
otel_enabled: true
resourceserver_enabled: true
redis_enabled: false
database_enabled: true

database:
  deploymentName: gradesdb-deployment
  serviceName: gradesdb
  appLabel: gradesdb
  name: gradesdb
  secretName: gradesdb-secret
  rootPassword: ""
  datasourceUrl: "jdbc:mysql://gradesdb:3306/gradesdb"
  image:
    repository: mysql
    tag: "8.0"
