apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.authKeysSecretName }}
type: Opaque
data:
  private.pem: {{ .Values.authKeys.privateKey | b64enc | quote }}
  public.pem: {{ .Values.authKeys.publicKey | b64enc | quote }}
