apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.usosSecretName }}
type: Opaque
data:
  USOS_CONSUMERKEY: {{ .Values.usosConsumerKey | b64enc | quote }}
  USOS_CONSUMERSECRET: {{ .Values.usosConsumerSecret | b64enc | quote }}
